# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' @keywords internal
#' 
NULL

#' Perform Gibbs sampling for mediation MR with correlation
#' 
#' Model is that Y = (I+B)A + noise
#' @param Y KxP arma::matrix of GWAS marginal associations
#' @param Sd_hat KxP arma::matrix of GWAS std errors
#' @param trait_corr KxK arma::matrix of correlation of noises.
#' @param N number of samples to obtain
#' @param B initial value of B arma::matrix
#' @param sigma Initial value of prior std deviation for values of B
#' @param sigma1 K-arma::vector of Initial values of prior slab SDs for each trait's pleiotropy
#' @param sigma0 K-arma::vector of Initial values of prior splike SDs for each trait's pleiotropy
#' @param p K-arma::vector of initial values for p, which is slab probability for mixture
#' @param A KxP arma::matrix of initial values for A (ignored)
#' @param Z KxP arma::matrix of initial values for Z (ignored), which is latent varaible indicating if A[i,j] comes from slab
#' @param alpha_B Shape parameter of InvGamma prior for sigma (for B)
#' @param beta_B Scale parameter of InvGamma prior for sigma (for B)
#' @param alpha_0 K-arma::vector Shape parameter of InvGamma prior for sigma0 (Spike)
#' @param alpha_1 K-arma::vector Shape parameter of InvGamma prior for sigma0 (Slab)
#' @param beta_0 K-arma::vector Scale parameter of InvGamma prior for sigma0 (Spike)
#' @param beta_1 K-arma::vector Scale parameter of InvGamma prior for sigma0 (Slab)
#' @param a K-arma::vector First parameter of beta prior for p
#' @param b K-arma::vector Second parameter of beta prior for p
#' @param Lambda3 Precomputed covariance matrix
#' @param Lambda_inv3 Precomputed inverse covariance matrix
#' @export
gibbs_sampler_with_corr <- function(Y, Sd_hat, trait_corr, N, B, sigma, sigma1, sigma0, p, A, Z, alpha_B, beta_B, alpha_0, alpha_1, beta_0, beta_1, a, b, Lambda3, Lambda_inv3) {
    .Call(`_MrMediation_gibbs_sampler_with_corr`, Y, Sd_hat, trait_corr, N, B, sigma, sigma1, sigma0, p, A, Z, alpha_B, beta_B, alpha_0, alpha_1, beta_0, beta_1, a, b, Lambda3, Lambda_inv3)
}

#' Perform Gibbs sampling for mediation MR without correlation
#' 
#' Model is that Y = (I+B)A + noise
#' @param Y KxP arma::matrix of GWAS marginal associations
#' @param Sd_hat KxP arma::matrix of GWAS std errors
#' @param N number of samples to obtain
#' @param B initial value of B arma::matrix
#' @param sigma Initial value of prior std deviation for values of B
#' @param sigma1 K-arma::vector of Initial values of prior slab SDs for each trait's pleiotropy
#' @param sigma0 K-arma::vector of Initial values of prior splike SDs for each trait's pleiotropy
#' @param p K-arma::vector of initial values for p, which is slab probability for mixture
#' @param A KxP arma::matrix of initial values for A (ignored)
#' @param Z KxP arma::matrix of initial values for Z (ignored), which is latent varaible indicating if A[i,j] comes from slab
#' @param alpha_B Shape parameter of InvGamma prior for sigma (for B)
#' @param beta_B Scale parameter of InvGamma prior for sigma (for B)
#' @param alpha_0 K-arma::vector Shape parameter of InvGamma prior for sigma0 (Spike)
#' @param alpha_1 K-arma::vector Shape parameter of InvGamma prior for sigma0 (Slab)
#' @param beta_0 K-arma::vector Scale parameter of InvGamma prior for sigma0 (Spike)
#' @param beta_1 K-arma::vector Scale parameter of InvGamma prior for sigma0 (Slab)
#' @param a K-arma::vector First parameter of beta prior for p
#' @param b K-arma::vector Second parameter of beta prior for p
#' 
#' @export
gibbs_sampler <- function(Y, Sd_hat, N, B, sigma, sigma1, sigma0, p, A, Z, alpha_B, beta_B, alpha_0, alpha_1, beta_0, beta_1, a, b) {
    .Call(`_MrMediation_gibbs_sampler`, Y, Sd_hat, N, B, sigma, sigma1, sigma0, p, A, Z, alpha_B, beta_B, alpha_0, alpha_1, beta_0, beta_1, a, b)
}

